In [10]:
# Example function: ADD
def add(x, y):
    return x+y

In [12]:
# Example of functino call
x=1
y=2
add(x,y)

3

In [13]:
def min(x,y):
    return x-y

In [14]:
x=3
y=3
min(x,y)

0

In [15]:
def multiple(x,y):
    return x*y
x=1
y=3
multiple(x,y)

3

In [2]:
def divide(x,y):
    if y==0:
        print ("error")
    else:
        return x/y
    
x=1
y=3
divide(x,y)

0.3333333333333333

In [4]:
import numpy as np

z=np.arange(13,dtype=np.uint8)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint8)

In [5]:
zz=z.astype(float)
zz

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [6]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
x=np.array((1,2,3))
x

array([1, 2, 3])

In [11]:
q=np.array([[1,2,3],[4,5,6],[7,8,9]])
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
x=np.ones((3,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [ ]:
a = 10 # 1010
b = 4  # 0100

# |
# 1 | 1 = 1
# 1 | 0 = 1
# 0 | 1 = 1
# 0 | 0 = 0

# &
# 1 & 1 = 1
# 1 & 0 = 0
# 0 & 1 = 0
# 0 & 0 = 0

# C => True, False X
# C => 0: False
# C => : True