In [1]:
# Example function: ADD
def add(x, y):
    return x+y

In [2]:
# Example of functino call
x=1
y=2
add(x,y)

3

In [3]:
def min(x,y):
    return x-y

In [4]:
x=3
y=3
min(x,y)

0

In [5]:
def multiple(x,y):
    return x*y
x=1
y=3
multiple(x,y)

3

In [6]:
def divide(x,y):
    if y==0:
        print ("error")
    else:
        return x/y
    
x=1
y=3
divide(x,y)

0.3333333333333333

In [7]:
import numpy as np

z=np.arange(13,dtype=np.uint8)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=uint8)

In [8]:
zz=z.astype(float)
zz

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [9]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [10]:
x=np.array((1,2,3))
x

array([1, 2, 3])

In [11]:
q=np.array([[1,2,3],[4,5,6],[7,8,9]])
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
x=np.ones((3,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.indices((2,2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [14]:
a = 10 # 1010
b = 4  # 0100

# |
# 1 | 1 = 1
# 1 | 0 = 1
# 0 | 1 = 1
# 0 | 0 = 0

# &
# 1 & 1 = 1
# 1 & 0 = 0
# 0 & 1 = 0
# 0 & 0 = 0

# C => True, False X
# C => 0: False
# C => : True

In [15]:
1<<3

8

In [16]:
print('hello world in your everything~')

hello world in your everything~


In [17]:
10**2

100

In [18]:
import pandas as pd
import numpy as np
import re
from scipy.stats import ttest_ind

In [19]:
convert=pd.read_csv('C:\\Users\\syjy0\\OneDrive\\바탕 화면\\전북대_산공\\GITHUB\\Open-Course\\UMICH-Introduction to Data Science in Python/City_Zhvi_AllHomes.csv')
#Multi Indexing
convert

RegionID           RegionName State                           Metro  \
0          6181             New York    NY                        New York   
1         12447          Los Angeles    CA  Los Angeles-Long Beach-Anaheim   
2         17426              Chicago    IL                         Chicago   
3         13271         Philadelphia    PA                    Philadelphia   
4         40326              Phoenix    AZ                         Phoenix   
...         ...                  ...   ...                             ...   
10725    398292  Town of Wrightstown    WI                       Green Bay   
10726    398343               Urbana    NY                         Corning   
10727    398496          New Denmark    WI                       Green Bay   
10728    398839               Angels    CA                             NaN   
10729    399114              Holland    WI                       Sheboygan   

         CountyName  SizeRank   1996-04   1996-05   1996-06   1996-07  ...  \
0            Queens         1       NaN       NaN       NaN       NaN  ...   
1       Los Angeles         2  155000.0  154600.0  154400.0  154200.0  ...   
2              Cook         3  109700.0  109400.0  109300.0  109300.0  ...   
3      Philadelphia         4   50000.0   49900.0   49600.0   49400.0  ...   
4          Maricopa         5   87200.0   87700.0   88200.0   88400.0  ...   
...             ...       ...       ...       ...       ...       ...  ...   
10725         Brown     10726       NaN       NaN       NaN       NaN  ...   
10726       Steuben     10727   66900.0   65800.0   65500.0   65100.0  ...   
10727         Brown     10728       NaN       NaN       NaN       NaN  ...   
10728     Calaveras     10729  115600.0  116400.0  118000.0  119000.0  ...   
10729     Sheboygan     10730  129900.0  130200.0  130300.0  129100.0  ...   

       2015-11  2015-12  2016-01  2016-02  2016-03  2016-04  2016-05  2016-06  \
0       573600   576200   578400   582200   588000   592200   592500   590200   
1       558200   560800   562800   565600   569700   574000   577800   580600   
2       207800   206900   206200   205800   206200   207300   208200   209100   
3       122300   121600   121800   123300   125200   126400   127000   127400   
4       183800   185300   186600   188000   189100   190200   191300   192800   
...        ...      ...      ...      ...      ...      ...      ...      ...   
10725   149900   150100   150300   150000   149200   149900   151400   152500   
10726   135700   136400   137700   138700   140500   143600   145000   144000   
10727   188700   189800   190800   191200   191200   191700   192800   194000   
10728   280400   279600   278000   276600   275000   273700   272000   269100   
10729   217800   219400   221100   222000   222800   224900   228000   231200   

       2016-07  2016-08  
0       588000   586400  
1       583000   585100  
2       211000   213000  
3       128300   129100  
4       194500   195900  
...        ...      ...  
10725   154100   155900  
10726   143000   143000  
10727   196300   198900  
10728   269000   270900  
10729   233900   236000  

[10730 rows x 251 columns]

In [23]:
df2=convert.loc[:,'2000-01':'2016-08']
sel_cols=df2.columns[df2.columns>='2000']
sel_cols=pd.to_datetime(sel_cols)
sel_cols.resample(rule='Q',axis=1).mean()

AttributeError: 'DatetimeIndex' object has no attribute 'resample'

In [25]:
df2.columns=pd.to_datetime(df2.columns)
df2

2000-01-01  2000-02-01  2000-03-01  2000-04-01  2000-05-01  2000-06-01  \
0             NaN         NaN         NaN         NaN         NaN         NaN   
1        204400.0    207000.0    209800.0    212300.0    214500.0    216600.0   
2        136800.0    138300.0    140100.0    141900.0    143700.0    145300.0   
3         52700.0     53100.0     53200.0     53400.0     53700.0     53800.0   
4        111000.0    111700.0    112800.0    113700.0    114300.0    115100.0   
...           ...         ...         ...         ...         ...         ...   
10725    101100.0    101500.0    102700.0    103700.0    105200.0    107300.0   
10726     77600.0     79400.0     80600.0     80200.0     81000.0     83800.0   
10727    113900.0    114000.0    115800.0    117600.0    119100.0    121100.0   
10728    148000.0    151200.0    153800.0    155600.0    156000.0    156100.0   
10729    150800.0    151000.0    151300.0    151000.0    150200.0    150300.0   

       2000-07-01  2000-08-01  2000-09-01  2000-10-01  ...  2015-11-01  \
0             NaN         NaN         NaN         NaN  ...      573600   
1        219000.0    221100.0    222800.0    224300.0  ...      558200   
2        146700.0    147900.0    149000.0    150400.0  ...      207800   
3         53800.0     54100.0     54500.0     54700.0  ...      122300   
4        115600.0    115900.0    116500.0    117200.0  ...      183800   
...           ...         ...         ...         ...  ...         ...   
10725    110000.0    111800.0    112300.0    112900.0  ...      149900   
10726     88700.0     92400.0     94000.0     96300.0  ...      135700   
10727    123900.0    126200.0    128100.0    129600.0  ...      188700   
10728    156900.0    157700.0    159700.0    164100.0  ...      280400   
10729    151900.0    153500.0    154300.0    154400.0  ...      217800   

       2015-12-01  2016-01-01  2016-02-01  2016-03-01  2016-04-01  2016-05-01  \
0          576200      578400      582200      588000      592200      592500   
1          560800      562800      565600      569700      574000      577800   
2          206900      206200      205800      206200      207300      208200   
3          121600      121800      123300      125200      126400      127000   
4          185300      186600      188000      189100      190200      191300   
...           ...         ...         ...         ...         ...         ...   
10725      150100      150300      150000      149200      149900      151400   
10726      136400      137700      138700      140500      143600      145000   
10727      189800      190800      191200      191200      191700      192800   
10728      279600      278000      276600      275000      273700      272000   
10729      219400      221100      222000      222800      224900      228000   

       2016-06-01  2016-07-01  2016-08-01  
0          590200      588000      586400  
1          580600      583000      585100  
2          209100      211000      213000  
3          127400      128300      129100  
4          192800      194500      195900  
...           ...         ...         ...  
10725      152500      154100      155900  
10726      144000      143000      143000  
10727      194000      196300      198900  
10728      269100      269000      270900  
10729      231200      233900      236000  

[10730 rows x 200 columns]

In [26]:
df2.resample(rule='Q',axis=1).mean()

2000-03-31     2000-06-30     2000-09-30     2000-12-31  \
0                NaN            NaN            NaN            NaN   
1      207066.666667  214466.666667  220966.666667  226166.666667   
2      138400.000000  143633.333333  147866.666667  152133.333333   
3       53000.000000   53633.333333   54133.333333   54700.000000   
4      111833.333333  114366.666667  116000.000000  117400.000000   
...              ...            ...            ...            ...   
10725  101766.666667  105400.000000  111366.666667  114866.666667   
10726   79200.000000   81666.666667   91700.000000   98366.666667   
10727  114566.666667  119266.666667  126066.666667  131966.666667   
10728  151000.000000  155900.000000  158100.000000  167466.666667   
10729  151033.333333  150500.000000  153233.333333  155833.333333   

          2001-03-31     2001-06-30     2001-09-30     2001-12-31  \
0                NaN            NaN            NaN            NaN   
1      233000.000000  239100.000000  245066.666667  253033.333333   
2      156933.333333  161800.000000  166400.000000  170433.333333   
3       55333.333333   55533.333333   56266.666667   57533.333333   
4      119600.000000  121566.666667  122700.000000  124300.000000   
...              ...            ...            ...            ...   
10725  125966.666667  129900.000000  129900.000000  129433.333333   
10726   94866.666667   98533.333333  102966.666667   98033.333333   
10727  143800.000000  146966.666667  148366.666667  149166.666667   
10728  176833.333333  183766.666667  190233.333333  184566.666667   
10729  161866.666667  165733.333333  168033.333333  167400.000000   

          2002-03-31     2002-06-30  ...     2014-06-30     2014-09-30  \
0                NaN            NaN  ...  515466.666667  522800.000000   
1      261966.666667  272700.000000  ...  498033.333333  509066.666667   
2      175500.000000  177566.666667  ...  192633.333333  195766.666667   
3       59133.333333   60733.333333  ...  113733.333333  115300.000000   
4      126533.333333  128366.666667  ...  164266.666667  165366.666667   
...              ...            ...  ...            ...            ...   
10725  131900.000000  134200.000000  ...  144866.666667  146866.666667   
10726   93966.666667   94600.000000  ...  132133.333333  137033.333333   
10727  153133.333333  156733.333333  ...  174566.666667  181166.666667   
10728  184033.333333  186133.333333  ...  244466.666667  254066.666667   
10729  165766.666667  161966.666667  ...  201266.666667  201566.666667   

          2014-12-31     2015-03-31     2015-06-30     2015-09-30  \
0      528066.666667  532266.666667  540800.000000  557200.000000   
1      518866.666667  528800.000000  538166.666667  547266.666667   
2      201266.666667  201066.666667  206033.333333  208300.000000   
3      115666.666667  116200.000000  117966.666667  121233.333333   
4      168500.000000  171533.333333  174166.666667  179066.666667   
...              ...            ...            ...            ...   
10725  149233.333333  148666.666667  149333.333333  149866.666667   
10726  140066.666667  141700.000000  137866.666667  136466.666667   
10727  186166.666667  187600.000000  188666.666667  188433.333333   
10728  259933.333333  260100.000000  250633.333333  263500.000000   
10729  201266.666667  206000.000000  207600.000000  212866.666667   

          2015-12-31     2016-03-31     2016-06-30  2016-09-30  
0      572833.333333  582866.666667  591633.333333    587200.0  
1      557733.333333  566033.333333  577466.666667    584050.0  
2      207900.000000  206066.666667  208200.000000    212000.0  
3      122200.000000  123433.333333  126933.333333    128700.0  
4      183833.333333  187900.000000  191433.333333    195200.0  
...              ...            ...            ...         ...  
10725  149933.333333  149833.333333  151266.666667    155000.0  
10726  136166.666667  138966.666667  144200.000000    143000.0  
10727  188933.333333  191066.666667  192833.33333